#!/usr/bin/env bash
#
# budget_check.sh — token-free 5-hour rolling-budget summary for the PM.
#
# Reads logs/usage.jsonl (written by dispatcher.sh) and rewrites a small Markdown
# block at the TOP of state/STATUS.md, between <!-- BUDGET:START/END --> markers,
# so the PM can read live utilization without recomputing or pulling raw logs into
# its own context. Uses only jq + date + awk — NO model, no tokens. Safe to run
# every tick and idempotent (it replaces its own block, never appends duplicates).
#
# Called by dispatcher.sh when telemetry.show_rolling_budget_in_status is true,
# or by hand:  ./scripts/budget_check.sh
#
# Resilient by design: any missing tool just exits 0 so it can never break a tick.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"; cd "$ROOT"
[ -f "$ROOT/.env" ] && { set -a; . "$ROOT/.env"; set +a; }

SCHEDULE="$ROOT/schedule.json"
USAGE="$ROOT/logs/usage.jsonl"
STATUS="$ROOT/state/STATUS.md"
mkdir -p "$ROOT/state" "$ROOT/logs"

command -v jq >/dev/null 2>&1 || exit 0

cap=$(jq -r '.soft_budget_usd_per_5h // 0' "$SCHEDULE" 2>/dev/null || echo 0)
now=$(date +%s)
cutoff=$(( now - 5*3600 ))

# Aggregate spend + per-agent run counts over the trailing 5h window (token-free).
if [ -f "$USAGE" ]; then
  spent=$(jq -s --argjson c "$cutoff" '[ .[] | select(.ts >= $c) | .cost ] | add // 0' "$USAGE" 2>/dev/null || echo 0)
  counts=$(jq -rs --argjson c "$cutoff" \
    '[ .[] | select(.ts >= $c) ] | group_by(.agent)
       | map("\(.[0].agent) \(length)") | join(" · ")' \
    "$USAGE" 2>/dev/null || echo "")
else
  spent=0; counts=""
fi
[ -z "$counts" ] && counts="none yet"

spent_fmt=$(jq -n --argjson s "$spent" '(($s*100)|round)/100' 2>/dev/null || echo "$spent")
stamp=$(date +%H:%M)

# A 14-cell bar when a soft cap is set; otherwise just the running total.
if [ "$cap" != "0" ]; then
  pct_int=$(jq -n --argjson s "$spent" --argjson b "$cap" 'if $b>0 then (($s/$b)*100|floor) else 0 end')
  [ "$pct_int" -gt 100 ] && pct_int=100
  filled=$(( pct_int * 14 / 100 ))
  bar=""; i=0
  while [ "$i" -lt 14 ]; do
    if [ "$i" -lt "$filled" ]; then bar="${bar}█"; else bar="${bar}░"; fi
    i=$(( i + 1 ))
  done
  budget_line="Spent: \$$spent_fmt / \$$cap soft cap  $bar ${pct_int}%"
else
  budget_line="Spent: \$$spent_fmt in last 5h (soft cap disabled)"
fi

block="<!-- BUDGET:START (auto-generated by budget_check.sh; do not edit by hand) -->
## 5h rolling budget — updated $stamp
$budget_line
Runs: $counts
<!-- BUDGET:END -->"

# Replace any existing block, then prepend the fresh one. Idempotent.
touch "$STATUS"
tmp=$(mktemp)
awk '
  /<!-- BUDGET:START/ { skip=1 }
  skip != 1 { print }
  /<!-- BUDGET:END -->/ { skip=0 }
' "$STATUS" > "$tmp"
# Drop leading blank lines left behind, then write: block + blank + remainder.
{ printf '%s\n\n' "$block"; sed '/./,$!d' "$tmp"; } > "$STATUS"
rm -f "$tmp"
exit 0
